version: '3.7'

services:
  publish-barshare-gbfs:
    image: ghcr.io/bbnavi/moqo2gbfs:main
    environment:
      - MOQO_ACCESS_TOKEN=${MOQO_ACCESS_TOKEN:?missing env var MOQO_ACCESS_TOKEN}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:?missing env var MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:?missing env var MINIO_SECRET_KEY}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - public

networks:
  public:
    external: true