name: build & deploy publish-barshare-gbfs Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: registry.gitlab.tpwd.de
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - name: build moqo2gbfs Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: moqo2gbfs
    - name: build & publish publish-barshare-gbfs Docker image
      uses: docker/build-push-action@v2
      with:
        context: publish-barshare-gbfs
        push: true
        tags: registry.gitlab.tpwd.de/tpwd/bb-navi/publish-barshare-gbfs
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: "${{ secrets.QUANTUM_USER }}"
      QUANTUM_PASSWORD: "${{ secrets.QUANTUM_PASSWORD }}"
      QUANTUM_ENDPOINT: "tpwd-bb-navi"
      QUANTUM_STACK: "publish-barshare-gbfs-tpwd-bb-navi"
      MOQO_ACCESS_TOKEN: "${{ secrets.MOQO_ACCESS_TOKEN }}"
      MINIO_ACCESS_KEY: "${{ secrets.MINIO_ACCESS_KEY }}"
      MINIO_SECRET_KEY: "${{ secrets.MINIO_SECRET_KEY }}"
    steps:
      - uses: actions/checkout@v2
      # https://twitter.com/derhuerst/status/1511660213111336961
      - name: inline env vars to work around quantum-cli support
        run: |
          cd publish-barshare-gbfs
          apk add --no-cache --upgrade docker-compose moreutils
          docker-compose -f quantum-stack.yml config | sponge quantum-stack.yml
      - name: deploy to bbnavi infrastructure
        run: |
          cd publish-barshare-gbfs
          quantum-cli stacks update --create --wait
